version: "3"

vars:
  GOFUMPT: go run mvdan.cc/gofumpt@latest
  STATICCHECK: go run honnef.co/go/tools/cmd/staticcheck@latest

tasks:
  default:
    desc: Build everything
    deps: [build]

  build:
    desc: Build frontend and Go binary
    deps: [build:frontend]
    cmds:
      - go build -o claude2stream .
    sources:
      - "*.go"
      - webui/dist/**/*

  build:frontend:
    desc: Build the Vite frontend
    dir: webui
    cmds:
      - pnpm install
      - pnpm build
    sources:
      - package.json
      - pnpm-lock.yaml
      - src/**/*
      - index.html
      - vite.config.*
    generates:
      - dist/**/*

  dev:
    desc: Run frontend dev server
    dir: webui
    cmds:
      - pnpm dev

  run:
    desc: Build and run the server
    deps: [build]
    cmds:
      - ./claude2stream

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf claude2stream webui/dist

  release:snapshot:
    desc: Test goreleaser locally (snapshot)
    deps: [build:frontend]
    cmds:
      - goreleaser release --snapshot --clean

  # ============================================================================
  # Precommit checks
  # ============================================================================

  fmt:
    desc: Format code with gofumpt
    cmds:
      - "{{.GOFUMPT}} -w ."

  fmt:check:
    desc: Check code formatting
    cmds:
      - "{{.GOFUMPT}} -d . | grep . && exit 1 || exit 0"

  staticcheck:
    desc: Run staticcheck
    cmds:
      - "{{.STATICCHECK}} ./..."

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  precommit:
    desc: Run all precommit checks
    cmds:
      - task: fmt:check
      - task: vet
      - task: staticcheck
      - echo "All precommit checks passed."
